In [28]:
!pip install polars

Requirement already satisfied: polars in /usr/local/lib/python3.12/dist-packages (1.35.2)
Requirement already satisfied: polars-runtime-32==1.35.2 in /usr/local/lib/python3.12/dist-packages (from polars) (1.35.2)

In [29]:
import polars as pl

In [30]:
df = pl.read_csv("/content/retail_store_sales.csv")

In [31]:
print(df.head)

<bound method DataFrame.head of shape: (12_575, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬──────────┬───────────┬───────────┐
│ Transacti ┆ Customer  ┆ Category  ┆ Item      ┆ … ┆ Payment   ┆ Location ┆ Transacti ┆ Discount  │
│ on ID     ┆ ID        ┆ ---       ┆ ---       ┆   ┆ Method    ┆ ---      ┆ on Date   ┆ Applied   │
│ ---       ┆ ---       ┆ str       ┆ str       ┆   ┆ ---       ┆ str      ┆ ---       ┆ ---       │
│ str       ┆ str       ┆           ┆           ┆   ┆ str       ┆          ┆ str       ┆ bool      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪══════════╪═══════════╪═══════════╡
│ TXN_68673 ┆ CUST_09   ┆ Patisseri ┆ Item_10_P ┆ … ┆ Digital   ┆ Online   ┆ 2024-04-0 ┆ true      │
│ 43        ┆           ┆ e         ┆ AT        ┆   ┆ Wallet    ┆          ┆ 8         ┆           │
│ TXN_37319 ┆ CUST_22   ┆ Milk      ┆ Item_17_M ┆ … ┆ Digital   ┆ Online   ┆ 2023-07-2 ┆ true      │
│ 86        ┆           ┆ Products  ┆ ILK       ┆   ┆ Wallet    ┆          ┆ 3         ┆           │
│ TXN_93037 ┆ CUST_02   ┆ Butchers  ┆ Item_12_B ┆ … ┆ Credit    ┆ Online   ┆ 2022-10-0 ┆ false     │
│ 19        ┆           ┆           ┆ UT        ┆   ┆ Card      ┆          ┆ 5         ┆           │
│ TXN_94581 ┆ CUST_06   ┆ Beverages ┆ Item_16_B ┆ … ┆ Credit    ┆ Online   ┆ 2022-05-0 ┆ null      │
│ 26        ┆           ┆           ┆ EV        ┆   ┆ Card      ┆          ┆ 7         ┆           │
│ TXN_45753 ┆ CUST_05   ┆ Food      ┆ Item_6_FO ┆ … ┆ Digital   ┆ Online   ┆ 2022-10-0 ┆ false     │
│ 73        ┆           ┆           ┆ OD        ┆   ┆ Wallet    ┆          ┆ 2         ┆           │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …        ┆ …         ┆ …         │
│ TXN_93474 ┆ CUST_18   ┆ Patisseri ┆ Item_23_P ┆ … ┆ Credit    ┆ In-store ┆ 2023-09-0 ┆ null      │
│ 81        ┆           ┆ e         ┆ AT        ┆   ┆ Card      ┆          ┆ 3         ┆           │
│ TXN_40094 ┆ CUST_03   ┆ Beverages ┆ Item_2_BE ┆ … ┆ Cash      ┆ Online   ┆ 2022-08-1 ┆ false     │
│ 14        ┆           ┆           ┆ V         ┆   ┆           ┆          ┆ 2         ┆           │
│ TXN_53060 ┆ CUST_11   ┆ Butchers  ┆ Item_7_BU ┆ … ┆ Cash      ┆ Online   ┆ 2024-08-2 ┆ null      │
│ 10        ┆           ┆           ┆ T         ┆   ┆           ┆          ┆ 4         ┆           │
│ TXN_51672 ┆ CUST_04   ┆ Furniture ┆ Item_7_FU ┆ … ┆ Cash      ┆ Online   ┆ 2023-12-3 ┆ true      │
│ 98        ┆           ┆           ┆ R         ┆   ┆           ┆          ┆ 0         ┆           │
│ TXN_24074 ┆ CUST_23   ┆ Food      ┆ Item_9_FO ┆ … ┆ Cash      ┆ Online   ┆ 2022-08-0 ┆ null      │
│ 94        ┆           ┆           ┆ OD        ┆   ┆           ┆          ┆ 6         ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴──────────┴───────────┴───────────┘>

In [32]:
print(df.columns)

['Transaction ID', 'Customer ID', 'Category', 'Item', 'Price Per Unit', 'Quantity', 'Total Spent', 'Payment Method', 'Location', 'Transaction Date', 'Discount Applied']

In [59]:
print(df.dtypes)

[String, String, String, String, Float64, Float64, Float64, String, String, String, Boolean]

In [33]:
print(df.shape)

(12575, 11)

In [34]:
print(df.select(['Price Per Unit','Quantity','Total Spent']).head())

shape: (5, 3)
┌────────────────┬──────────┬─────────────┐
│ Price Per Unit ┆ Quantity ┆ Total Spent │
│ ---            ┆ ---      ┆ ---         │
│ f64            ┆ f64      ┆ f64         │
╞════════════════╪══════════╪═════════════╡
│ 18.5           ┆ 10.0     ┆ 185.0       │
│ 29.0           ┆ 9.0      ┆ 261.0       │
│ 21.5           ┆ 2.0      ┆ 43.0        │
│ 27.5           ┆ 9.0      ┆ 247.5       │
│ 12.5           ┆ 7.0      ┆ 87.5        │
└────────────────┴──────────┴─────────────┘

In [35]:
df.null_count()

shape: (1, 11)
┌──────────────┬──────────────┬──────────┬──────┬───┬─────────┬──────────┬──────────────┬──────────┐
│ Transaction  ┆ Customer ID  ┆ Category ┆ Item ┆ … ┆ Payment ┆ Location ┆ Transaction  ┆ Discount │
│ ID           ┆ ---          ┆ ---      ┆ ---  ┆   ┆ Method  ┆ ---      ┆ Date         ┆ Applied  │
│ ---          ┆ u32          ┆ u32      ┆ u32  ┆   ┆ ---     ┆ u32      ┆ ---          ┆ ---      │
│ u32          ┆              ┆          ┆      ┆   ┆ u32     ┆          ┆ u32          ┆ u32      │
╞══════════════╪══════════════╪══════════╪══════╪═══╪═════════╪══════════╪══════════════╪══════════╡
│ 0            ┆ 0            ┆ 0        ┆ 1213 ┆ … ┆ 0       ┆ 0        ┆ 0            ┆ 4199     │
└──────────────┴──────────────┴──────────┴──────┴───┴─────────┴──────────┴──────────────┴──────────┘

In [49]:
df = df.with_columns(
  pl.when(pl.col("Price Per Unit").is_null())
  .then(
      pl.col("Total Spent")/pl.col("Quantity")
  )
  .otherwise(pl.col("Price Per Unit"))
  .alias("Price Per Unit")
 )

In [50]:
df = df.with_columns(
    pl.when(pl.col("Quantity").is_null())
    .then(
        pl.col("Total Spent") / pl.col("Price Per Unit")
    )
  .otherwise(pl.col("Quantity"))
  .alias("Quantity")
)

In [51]:
df = df.with_columns(
    pl.when(pl.col("Total Spent").is_null())
    .then(
        pl.col("Price Per Unit") * pl.col("Quantity")
    )
  .otherwise(pl.col("Total Spent"))
  .alias("Total Spent")
)

In [52]:
df.null_count()

shape: (1, 11)
┌──────────────┬──────────────┬──────────┬──────┬───┬─────────┬──────────┬──────────────┬──────────┐
│ Transaction  ┆ Customer ID  ┆ Category ┆ Item ┆ … ┆ Payment ┆ Location ┆ Transaction  ┆ Discount │
│ ID           ┆ ---          ┆ ---      ┆ ---  ┆   ┆ Method  ┆ ---      ┆ Date         ┆ Applied  │
│ ---          ┆ u32          ┆ u32      ┆ u32  ┆   ┆ ---     ┆ u32      ┆ ---          ┆ ---      │
│ u32          ┆              ┆          ┆      ┆   ┆ u32     ┆          ┆ u32          ┆ u32      │
╞══════════════╪══════════════╪══════════╪══════╪═══╪═════════╪══════════╪══════════════╪══════════╡
│ 0            ┆ 0            ┆ 0        ┆ 1213 ┆ … ┆ 0       ┆ 0        ┆ 0            ┆ 4199     │
└──────────────┴──────────────┴──────────┴──────┴───┴─────────┴──────────┴──────────────┴──────────┘

In [53]:
df = df.drop_nulls()

In [54]:
df.null_count()

shape: (1, 11)
┌──────────────┬──────────────┬──────────┬──────┬───┬─────────┬──────────┬──────────────┬──────────┐
│ Transaction  ┆ Customer ID  ┆ Category ┆ Item ┆ … ┆ Payment ┆ Location ┆ Transaction  ┆ Discount │
│ ID           ┆ ---          ┆ ---      ┆ ---  ┆   ┆ Method  ┆ ---      ┆ Date         ┆ Applied  │
│ ---          ┆ u32          ┆ u32      ┆ u32  ┆   ┆ ---     ┆ u32      ┆ ---          ┆ ---      │
│ u32          ┆              ┆          ┆      ┆   ┆ u32     ┆          ┆ u32          ┆ u32      │
╞══════════════╪══════════════╪══════════╪══════╪═══╪═════════╪══════════╪══════════════╪══════════╡
│ 0            ┆ 0            ┆ 0        ┆ 0    ┆ … ┆ 0       ┆ 0        ┆ 0            ┆ 0        │
└──────────────┴──────────────┴──────────┴──────┴───┴─────────┴──────────┴──────────────┴──────────┘

In [55]:
print(df.shape)

(7579, 11)

In [58]:
df.write_csv("Store_sales_clean.csv")